library(ggplot2)
library(Kaashi)
square = regularPolygon(12)
tile <- motif(square,n = 12, theta = 30, delta = 0, polyLine = F, dist = 0.1,midpoint = c(1,1))
daily_minimal_plot(tile,"daily_motif/day_002/day_002.png",type = "png",caption = "Daily Motif\n\nNO. 2")
